name: Publish to PyPI

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Adjust the Python version to your project's requirements

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Build and publish to PyPI
      run: |
        python setup.py sdist bdist_wheel
        python -m twine upload dist/*
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
